name: input demo 3

on: 
  workflow_dispatch:
    inputs:
      environment:
       description: Choose the environnent to deploy
       required: true
       default: dev
     
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
    - name: deploying inputs
      run: echo "deployint the app to the ${{ inputs.environment}}"
      
   
  
